Merging branch 0.2.8 from revision 9258 to 9322:  ------------------------------------------------------------------------  r9322 | z-man | 2010-01-23 10:04:28 +0100 (Sat, 23 Jan 2010) | 3 lines
 Added subcultures to dedicated installer, too. They're not used, but
 admins may want to see the list.
 
 ------------------------------------------------------------------------
 r9321 | z-man | 2010-01-23 10:03:15 +0100 (Sat, 23 Jan 2010) | 2 lines
 
 Adding subculture file to installer.
 
 ------------------------------------------------------------------------
 r9320 | bazaarmagetron | 2010-01-23 02:17:52 +0100 (Sat, 23 Jan 2010) | 2 lines
 
 Manuel Moos: Fixing missing distribution of subcultures.srv.
 
 ------------------------------------------------------------------------
 r9317 | bazaarmagetron | 2010-01-20 23:31:22 +0100 (Wed, 20 Jan 2010) | 2 lines
 
 Manuel Moos: Quicker help texts and organically accelerating key repeat for friendlier menus.
 
 ------------------------------------------------------------------------
 r9316 | bazaarmagetron | 2010-01-20 23:13:21 +0100 (Wed, 20 Jan 2010) | 1 line
 
 Manuel Moos: Fixed typos.
 ------------------------------------------------------------------------
 r9315 | bazaarmagetron | 2010-01-20 22:16:30 +0100 (Wed, 20 Jan 2010) | 2 lines
 
 Manuel Moos: Added shuffle suppression texts.
 
 ------------------------------------------------------------------------
 r9314 | bazaarmagetron | 2010-01-19 02:28:41 +0100 (Tue, 19 Jan 2010) | 2 lines
 
 Manuel Moos: Sound no loger stops for entire rounds if you alt-tab away.
 
 ------------------------------------------------------------------------
 r9312 | bazaarmagetron | 2010-01-16 21:22:59 +0100 (Sat, 16 Jan 2010) | 8 lines
 
 author: Manuel Moos
 Improved server behaviour during fullscreen message display. Before,
 it would wait for the clients to finish directly; that caused trouble,
 because the message usually is triggered by a network message from a
 remote admin, which means the server is in packet receiving state and
 it should quit from that state ASAP to avoid side effects. Now, the
 waiting is done in a background task stated via the st_Todo mechanism.
 
 ------------------------------------------------------------------------
 r9311 | bazaarmagetron | 2010-01-16 21:20:53 +0100 (Sat, 16 Jan 2010) | 2 lines
 
 Manuel Moos: Moving server comparison change to the server info comparison function where it belongs.
 
 ------------------------------------------------------------------------
 r9310 | bazaarmagetron | 2010-01-16 19:02:21 +0100 (Sat, 16 Jan 2010) | 1 line
 
 Manuel Moos: All INETADDR_ANY IPs now compare as unequal to avoid server deletion rampages during a DNS server outage.
 ------------------------------------------------------------------------
 r9309 | bazaarmagetron | 2010-01-16 19:01:46 +0100 (Sat, 16 Jan 2010) | 2 lines
 
 Manuel Moos: Made GCC happy, again.
 
 ------------------------------------------------------------------------
 r9308 | bazaarmagetron | 2010-01-16 03:07:53 +0100 (Sat, 16 Jan 2010) | 2 lines
 
 Manuel Moos: Updated news.
 
 ------------------------------------------------------------------------
 r9307 | bazaarmagetron | 2010-01-16 00:32:44 +0100 (Sat, 16 Jan 2010) | 2 lines
 
 Manuel Moos: Disabling pathfinding if it takes too long. Doesn't do too much good, anyway, a typical player will chase the AIs down actively.
 
 ------------------------------------------------------------------------
 r9306 | bazaarmagetron | 2010-01-15 22:39:05 +0100 (Fri, 15 Jan 2010) | 2 lines
 
 Manuel Moos: Speeding up default server pinging by a factor of two. Should still not totally break down on ISDN or fast dialup, definitely no problem for crappy WLAN or even the slowest form of DSL.
 
 ------------------------------------------------------------------------
 r9305 | bazaarmagetron | 2010-01-14 23:41:42 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Avoiding DNS lookups while still connected to the master server, if possible.
 
 ------------------------------------------------------------------------
 r9304 | bazaarmagetron | 2010-01-14 23:41:08 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: On conflicting information, prefer to keep the IP version of server infos to avoid needless DNS loopups.
 
 ------------------------------------------------------------------------
 r9303 | bazaarmagetron | 2010-01-14 23:40:35 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Removing duplicate servers where one copy uses SERVER_DNS, the other not, right as they come in from the network.
 
 ------------------------------------------------------------------------
 r9302 | bazaarmagetron | 2010-01-14 23:40:00 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Adapted German translation a bit to new terminology.
 
 ------------------------------------------------------------------------
 r9301 | bazaarmagetron | 2010-01-14 23:39:25 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Speeding up fast finish some more.
 
 ------------------------------------------------------------------------
 r9300 | bazaarmagetron | 2010-01-14 23:38:48 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Reorganized main game menu items to make internet multiplayer easier to access.
 
 ------------------------------------------------------------------------
 r9299 | bazaarmagetron | 2010-01-14 23:38:04 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Eating input the player made while the server list was fetched to avoid him going to host a game or quitting immediately.
 
 ------------------------------------------------------------------------
 r9298 | bazaarmagetron | 2010-01-14 10:30:19 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Speeding up fast finish.
 
 ------------------------------------------------------------------------
 r9297 | bazaarmagetron | 2010-01-14 10:29:05 +0100 (Thu, 14 Jan 2010) | 2 lines
 
 Manuel Moos: Fixed bug where a round would go on forever if the last survivors where AIs outliving their humans by quite a bit, then getting killed sufficiently simultaneously.
 
 ------------------------------------------------------------------------
 r9296 | bazaarmagetron | 2010-01-12 02:14:39 +0100 (Tue, 12 Jan 2010) | 1 line
 
 Daniel Lee Harple: Use colored name for shuffle messages.
 ------------------------------------------------------------------------
 r9295 | bazaarmagetron | 2010-01-11 23:27:10 +0100 (Mon, 11 Jan 2010) | 7 lines
 
 author: Manuel Moos
 Without armathentication built in, now all console commands stay
 at ADMIN access level so remote admins can actually use them. One
 exception: the now activated ACCESS_LEVEL can only be invoked from the
 console or config files by default and thus allows disabling commands
 for remote admins.
 
 ------------------------------------------------------------------------
 r9288 | bazaarmagetron | 2009-12-25 04:17:21 +0100 (Fri, 25 Dec 2009) | 2 lines
 
 Daniel Lee Harple: Do not extract whitespace from authentication params using std::ws()—it will not stop at a newline character. tString::ReadLine() will extract whitespace in the behavior we expect. Fixes bug #492844.
 
 ------------------------------------------------------------------------
 r9286 | bazaarmagetron | 2009-11-06 18:42:34 +0100 (Fri, 06 Nov 2009) | 1 line
 
 Daniel Lee Harple: Intercepted chat commands are now written to ladderlog.txt.
 ------------------------------------------------------------------------
 r9285 | bazaarmagetron | 2009-11-04 21:34:32 +0100 (Wed, 04 Nov 2009) | 2 lines
 
 Daniel Lee Harple: Use log name for intercepted chat commands
 
 ------------------------------------------------------------------------
 r9280 | bazaarmagetron | 2009-10-11 21:50:14 +0200 (Sun, 11 Oct 2009) | 2 lines
 
 Manuel Moos: Improved master server random polling, the second polled master now also is random, and all masters are polled if need be
 
 ------------------------------------------------------------------------
 r9279 | bazaarmagetron | 2009-10-11 21:47:01 +0200 (Sun, 11 Oct 2009) | 2 lines
 
 Manuel Moos: Storing server score between visits to the master list and polling higher scored servers first.
 
 ------------------------------------------------------------------------
 r9276 | bazaarmagetron | 2009-09-27 02:57:42 +0200 (Sun, 27 Sep 2009) | 2 lines
 
 Manuel Moos: Fixed typo.
 
 ------------------------------------------------------------------------
 r9272 | bazaarmagetron | 2009-09-18 22:51:44 +0200 (Fri, 18 Sep 2009) | 1 line
 
 Daniel Lee Harple: USER_LEVEL now escapes the given authenticated name
 ------------------------------------------------------------------------
 r9271 | bazaarmagetron | 2009-09-17 10:48:57 +0200 (Thu, 17 Sep 2009) | 2 lines
 
 Manuel Moos: Making GCC 4.3 happy.
 
 ------------------------------------------------------------------------
 r9270 | bazaarmagetron | 2009-09-16 21:09:28 +0200 (Wed, 16 Sep 2009) | 2 lines
 
 Manuel Moos: Zero turn speed custom camera now aligns with cycle when it is first set.
 
 ------------------------------------------------------------------------
 r9269 | bazaarmagetron | 2009-09-16 21:08:07 +0200 (Wed, 16 Sep 2009) | 2 lines
 
 Manuel Moos: Removing warning about failed setting the network TOS to realtime.
 
 ------------------------------------------------------------------------
 r9268 | bazaarmagetron | 2009-09-16 21:06:32 +0200 (Wed, 16 Sep 2009) | 2 lines
 
 Manuel Moos: Fixing missing output parameter in $player_joins_team_noex.
 
 ------------------------------------------------------------------------
 r9267 | bazaarmagetron | 2009-09-11 23:28:24 +0200 (Fri, 11 Sep 2009) | 4 lines
 
 author: Manuel Moos
 RESERVE_SCREEN_NAME now works regardless of the ALLOW_IMPOSTOR setting.
 Corrected and clarified RESERVE_SCREEN_NAME documentation.
 
 ------------------------------------------------------------------------
 r9266 | z-man | 2009-09-11 19:07:33 +0200 (Fri, 11 Sep 2009) | 2 lines
 
 Release notes are now uploaded with DOS encoding.
 
 ------------------------------------------------------------------------
 r9265 | z-man | 2009-09-11 18:59:19 +0200 (Fri, 11 Sep 2009) | 2 lines
 
 Adapted to new SF upload system, added release notes.
 
 ------------------------------------------------------------------------
 r9263 | bazaarmagetron | 2009-09-11 16:06:10 +0200 (Fri, 11 Sep 2009) | 2 lines
 
 Manuel Moos: Ignoring custom.txt; it doesn't exist by default and is unlikely to be complete.
 
 ------------------------------------------------------------------------
 r9260 | bazaarmagetron | 2009-09-11 15:17:05 +0200 (Fri, 11 Sep 2009) | 1 line
 
 Manuel Moos: Updated with news.
 ------------------------------------------------------------------------